name: CD - Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      #Authenticate to Google Cloud (usando tu secreto JSON)
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      #Configure gcloud CLI (activar cuenta)
      - name: Configure gcloud
        run: |
          gcloud auth activate-service-account --key-file=${{ steps.auth.outputs.credentials_file_path }}
          gcloud config set project flight-api-nicolramirez
          gcloud config set compute/region us-central1
          gcloud auth list

      #Build and push Docker image
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/flight-api-nicolramirez/delay-api .

      #Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy delay-api \
            --image gcr.io/flight-api-nicolramirez/delay-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
